schema_version: 1

context:
  name: glyphx
  version: "2.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/glyphx-${{ version }}.tar.gz
  sha256: 848c34a2111479b4a209f090dc6b59b2f6d84fbca3b7fd53da3fcde4ae038571

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - numpy
    - ipython
    - ipywidgets
    - pandas
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.21
    - pandas >=1.4.2
    - scipy >=1.7
    - cairosvg >=2.5
    - ipython >=7.0
    - ipywidgets >=8.1

tests:
  - python:
      imports:
        - glyphx
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/kjkoeller/glyphx
  documentation: https://glyphx.readthedocs.io/
  summary: A next-gen Python plotting library with SVG-first rendering, interactivity, themes, and clean defaults.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
